name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "ver/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: gradle/wrapper-validation-action@main
      - name: Setup Java JDK
        uses: graalvm/setup-graalvm@main
        with:
          java-version: 17
          distribution: graalvm
          cache: 'gradle'
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --no-daemon --stacktrace
      - name: Build
        run: ./gradlew build --no-daemon --stacktrace
      - name: CreateReobf Jar
        run: ./gradlew createReobfPaperclipJar
      - name: Rebuild on Failure
        if: ${{ failure() }}
        run: |
          ./gradlew clean cleanCache
          ./gradlew applyPatches --no-daemon --stacktrace 
          ./gradlew build --no-daemon --stacktrace
      - name: Upload jar
        uses: actions/upload-artifact@main
        with:
          name: PurpurTest
          path: |
            build/libs/
          compression-level: 9

      - name: Generate Build Summary
        uses: actions/github-script@main
        with:
          script: |
            core.summary
              .write()